apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, hector, role:readonly
    p, role:watcher, applications, get, */*, allow
    p, role:watcher, applications, get, default/*, deny
    p, role:watcher, project, get, *, allow
    p, role:watcher, project, get, default, deny
    p, role:app-manager, project, *, hector, allow
    p, role:app-manager, applications, *, hector/*, allow
    g, david, role:watcher
    g, hector, role:watcher


